### ISSUE TITLE
Version des Jobs mit loggen

### ISSUE THREAD

**Issue by cimttja** [cimt-ag/talendcomp_tJobInstance#1]
Es wäre wünschenswert, dass das Job InstanceFramework die Job-Version mit in den Tabellen abspeichert.
Vorstellbar wäre, dass man direkt auf die Variable "jobVersion" zu greift und diese weg sichert, oder wie in anderen Fällen als Freitext in den Komponenten.

**Comment by jlolling** [comment]
The version and other information are already there. Checkout the field job_info
